name: Release

on:
  push:
    tags:
      - 'v*.*.*'        # Triggers on version tags like v1.2.3
  workflow_dispatch:     # Allow manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Extract version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/cristian-release-prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract base version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create pre-release version string
        id: pre_version
        run: |
          DATE=$(date +'%Y%m%d')
          RUN_ID=${{ github.run_number }}
          PRE_VERSION="${{ steps.get_version.outputs.version }}-pre-${DATE}.${RUN_ID}"
          echo "pre_version=$PRE_VERSION" >> $GITHUB_OUTPUT
          echo "$PRE_VERSION" > version.txt  # temporary override

      - name: Build pre-release
        run: |
          python setup.py sdist bdist_wheel

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.pre_version.outputs.pre_version }}
          name: "Pre-release ${{ steps.pre_version.outputs.pre_version }}"
          prerelease: true
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
