name: Build, Release & Publish

on:
  push:
    branches:
      - main
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Stamp version.txt from Git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Strip leading "v" from ref name → e.g. v1.2.3 → 1.2.3
          echo "${VERSION#v}" > version.txt

      - name: Install packaging tools
        run: pip install --upgrade pip setuptools wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          twine upload \
            --repository-url https://upload.pypi.pkg.github.com/${{ github.repository_owner }}/ \
            dist/*

      - name: Bump to next pre-release on main
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract semantic parts
          TAG="${VERSION#v}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG"

          # Next patch with "-pre"
          NEXT_PATCH=$((PATCH + 1))
          PREVER="$MAJOR.$MINOR.$NEXT_PATCH-pre"

          # Update main branch version.txt
          git fetch origin main
          git checkout main
          echo "$PREVER" > version.txt

          # Commit & push bump (skip CI)
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to $PREVER for next pre-release [skip ci]" || echo "No changes to commit"
          git push origin main
